### PR TITLE
v2; complete rework

### PR DESCRIPTION
**Pull request by Adjokip**
Has been completely reworked to make much more use out of Javascript.

Features:
-Agents are loaded via Javascript. This is good for users with multiple
agents or when several are offline - faster load times!

-You can send any command to agents now. This is NOT some kind of
web-console - commands and their user access is defined in a config
file. By default, everyone (subusers, users, and admins) has access to
ping. Only admins have access to traceroute. Read the config file to see
how to define more commands. The text input field does NOT accept special characters - making inserting more commands via the text input impossible, I hope.

-The Steam Converter page now supports the Steam ID3 ( [U:1:xxxxxxxx] )
format.

-Users may only add Sourcemod admins if they meet the required permissions set in the config file (by default, they require the same access level as ftp and file manager access)

-The page doesn't reload for switching between custom sourcemod flags
and root admin.... actually, it doesn't reload at all now.

-HTML5 form elements are used such at pattern, along with checking if
the input is valid via JS and also via PHP. Check the input everywhere!

-The Mani Admin page was removed - it hasn't been supported since 2012
or so.

...It should be relatively simple to add support for other mods besides
Sourcemod via a few simple checks. But for now, this replicates the
basic functionality while being a bit more useful.

One thing to note: Since I'm sending requests to other scripts in the module directory (to make so much use out of JS), I have to do some hacky code in those scripts... as they need access to some core OGP files. One way to fix this is have OGP include stuff via the absolute path rather than relative.

### CODE REVIEW

**Comment by Zorrototo** [comment]
Nice work, will try it after approval :)

I see you have put the lang files in **modules/util/lang/xxx/modules/** is it intended to be like that? in theory lang files are stored in **/lang/xxx/modules/**

**Comment by Adjokip** [comment]
Good catch, they do seem to be in the wrong place.

On my test setup the util language file was placed and edited directly where all the other files are. Before committing I glanced over how other modules handle language files. 

Good thing it was noticed, everything except from one or two strings are all defined there. 

I can't fix it atm as I'm on mobile, but maintainers can make edits to the commit.

**Comment by own3mall** [comment]
Can't really comment on this code... I didn't write the original module.  Assuming it works, sure, we'll go with it.

**Comment by own3mall** [comment]
We can always revert or fix issues later.

**Comment by Zorrototo** [comment]
I installed it, clicked on the menu link "Util", and I have this message: "Loading Agents Failed."
I try to query on the steamId page and got this response: "The POST action failed. Unable to retrieve a response."

Is there something to do after installing it?

**Comment by Adjokip** [comment]
There's nothing to do after installing it. It works fine in production-like, and live environment (which freshly downloaded the Module)

If those messages appear, then the fail() jQuery function is being triggered. I'm guessing the loading icon appears for a second or so? It might be the PHP error reporting... the OGP core seems to run with minimal error reporting, so try setting `display_errors` to `false` in the config.inc.php file.

**Comment by Zorrototo** [comment]
Are you sure you talk about the good file to modify for errors? I do not have this setting in my config.inc.php for OGP. Isn't it in PHP.ini that this kind of stuff may be modified to show errors?

//edit//
after enabling display_errors = On in my php.ini and restarting Apache, still does not show any error.

**Comment by Adjokip** [comment]
Ah, sorry I meant `/modules/util/util_config.php` as that is included in the module and all of the required scripts (of which don't call the `exec_ogp_module` function as it would render a page - and the scripts need to return JSON data)

You can use `ini_set('display_errors', false);` in the aforementioned file as long as your server settings allow it. Additionally, make sure you've got no .htaccess file or nginx conf blocking for direct access to the modules directory. The way it works is, the `util` page loads and then requests `/modules/util/agents.php` via ajax to load the data for agent info. Same for all post requests, but to different files - the files check if the user is logged in.

This way no page refreshes are necessary, and loading is near instantaneous.

**Comment by Zorrototo** [comment]
I added this to the beginning of the config file, and still same problems (and yes I see for a micro second the loading icon).

**Comment by Adjokip** [comment]
I contacted @Zorrototo thought a more direct means and we found the issue. His installation is in a sub-directory, all of the `$.post` and `$.getJSON` jQuery calls assume the installation is in the root.

Just need to remove the first forward slash on each of these functions to fix this.

**Pull request merged**
